const newReleaseData = [
  {
    h1: "Simple way of piece life",
    p: " Armor Ramsey",
    span: "$ 40.00",
    img: "/book1.png",
    btn: "add to cart",
    slug: "item1",
  },
  {
    h1: "Great travel at desert",
    p: "Sanchit Howdy",
    span: "$ 38.00",
    img: "/book2.png",
    btn: "add to cart",
    slug: "item2",
  },
  {
    h1: "The lady beauty Scarlett",
    p: " Arthur Doyle",
    span: "$ 45.00",
    img: "/book3.png",
    btn: "add to cart",
    slug: "item3",
  },
  {
    h1: "Once upon a time",
    p: " Klien Marry",
    span: "$ 35.00",
    img: "/book4.png",
    btn: "add to cart",
    slug: "item4",
  },
  {
    h1: "Simple way of piece life",
    p: " Armor Ramsey",
    span: "$ 40.00",
    img: "/book1.png",
    btn: "add to cart",
    slug: "item5",
  },
  {
    h1: "Great travel at desert",
    p: "Sanchit Howdy",
    span: "$ 38.00",
    img: "/book2.png",
    btn: "add to cart",
    slug: "item6",
  },
  {
    h1: "The lady beauty Scarlett",
    p: " Arthur Doyle",
    span: "$ 45.00",
    img: "/book3.png",
    btn: "add to cart",
    slug: "item7",
  },
  {
    h1: "Once upon a time",
    p: " Klien Marry",
    span: "$ 35.00",
    img: "/book4.png",
    btn: "add to cart",
    slug: "item8",
  },
];
export default newReleaseData;
